# Generated by Django 4.1.7 on 2023-04-07 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_category_options_alter_category_input_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('all_topic', models.CharField(max_length=255)),
            ],
        ),
    ]
